apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb.fullname" . }}-init
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
data:
  init-mongo.sh: |
    #!/bin/bash
    set -e
    
    mongo <<EOF
    use admin
    db.auth('$MONGO_INITDB_ROOT_USERNAME', '$MONGO_INITDB_ROOT_PASSWORD')
    
    use $MONGODB_DATABASE
    db.createUser({
      user: '$MONGODB_USERNAME',
      pwd: '$MONGODB_PASSWORD',
      roles: [
        {
          role: 'readWrite',
          db: '$MONGODB_DATABASE'
        }
      ]
    })
    
    print('Created user: ' + '$MONGODB_USERNAME' + ' for database: ' + '$MONGODB_DATABASE')
    EOF