# Default values for guestbook-backend
nameOverride: ""
fullnameOverride: ""

image:
  repository: python-guestbook-backend
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

env:
  port: "8080"

# MongoDB connection secret
mongodb:
  existingSecret: ""
  usernameKey: "mongodb-username"
  passwordKey: "mongodb-password"
  databaseKey: "mongodb-database"
  connectionKey: "mongodb-connection"

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "100m"

nodeSelector: { }
tolerations: [ ]
affinity: { }

# Health checks
livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /ready
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

# Metrics configuration for Prometheus scraping
metrics:
  enabled: true
  path: /metrics
  port: 8080
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  
  # ServiceMonitor configuration for Prometheus Operator
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus  # Required for Prometheus discovery
    endpoint:
      port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s